### ISSUE TITLE
Extraction fails when header cell contains integers/floats

### ISSUE THREAD

**Issue by zarino** [scraperwiki/spreadsheet-upload-tool#1]
Once extract.py finds the header row, it should cast each cell to a String before using the cell values at keys for the data columns.

Otherwise, when scraperwiki.sqlite.save() attempts to save the data (as a list of dictionaries with some troublesome non-string keys) the save fails.

**Comment by zarino** [comment]
![screen shot 2013-04-30 at 10 55 16](https://f.cloud.github.com/assets/739624/443357/140de956-b17c-11e2-8ec7-cd0b91b68c9e.png)

Use the [qep211.xls](https://github.com/scraperwiki/spreadsheet-upload-tool/blob/master/fixture/qep211.xls) file to reproduce.

**Comment by frabcus** [comment]
Not relevant to new version of tool
