### ISSUE TITLE
Error when uploading XLS file created by spreadsheet download

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/spreadsheet-upload-tool#17]
When uploading a spreadsheet that has been created by the spreadsheet download tool we get the following error:

```
FileTypeError Unknown file type Composite Document File V2 Document, No summary info (I only understand .csv, .xls and .xlsx)
```

Here it is:

http://pwaller.net/sw/all_tables.xls

**Comment by IanHopkinson** [comment]
This file, downloaded as spreadsheet from :

https://www.dropbox.com/s/nnumy37kv7lntlp/agriaaffaires.co.uk.xls

Fails to upload, when upload is as xls the error message is:

```
Oh no! We received an unexpected error while structuring your spreadsheet: KeyError u'year'
```

The spreadsheet has 3 tabs and the key "year" occurs twice but changing one instance of year to something else does not help.

Trying to upload just the first sheet as csv gives this error:

```
Oh no! We received an unexpected error while structuring your spreadsheet: UnicodeDecodeError 'ascii' codec can't decode byte 0x81 in position 1: ordinal not in range(128)
```

**Comment by zarino** [comment]
I think we can file this under the "would probably be fixed by using Messytables" tag.
